rbacFile = "configs/rbac.conf"

[db]
[db.mysql]
host = "172.16.7.120"
port = 3306
user = "micro"
password = "micro"
db = "apsmgm"

[db.redis]
host = "redis"
port = 6379

[grpc]
host = "userservice"
port = 5000

[consul]
host = "consul"
port = 8500

[log]
path = "log"
file = "userservice.log"

[watcher]
addr = "0.0.0.0:9000"