rbacFile = "configs/rbac.conf"

[db]
[db.mysql]
host = "127.0.0.1"
port = 3306
user = "root"
password = "root"
db = "apsmgm"

[db.redis]
host = "redis"
port = 6379

[grpc]
host = "userservice"
port = 5000

[consul]
host = "consul"
port = 8500

[log]
path = "log"
file = "userservice.log"